apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-proxy
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents-proxy
  template:
    metadata:
      labels:
        app: agents-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: agents-proxy-nginx
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: agents-proxy
  namespace: agents
spec:
  selector:
    app: agents-proxy
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
